### ISSUE TITLE
Compiling for Windows as Standalone

### ISSUE THREAD

**Issue by rgleason** [RooieDirk/Deviation_pi#1]
Dirk, 
I tried it as standalone again.

All these errors are the same and from not including a tinyxml directory with the files and adapting the include paths.
However, I believe they now have tinyxml embedded more in OPencpn and it may just require a tinyxml.lib (I am probably wrong about this, see bdbcat comment in the forum http://www.cruisersforum.com/forums/f134/beta-test-technical-30929.html#post2528869  )that is added.  I am not a programmer guru, but I think Pavel or Bdbcat could give you the answer pretty quickly.

Best
Rick

```
Build FAILED.

"D:\Frederick\Documents\GitHub\Deviation_pi\build\ALL_BUILD.vcxproj" (default t
arget) (1) ->
"D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj" (defaul
t target) (3) ->
(ClCompile target) ->
  d:\frederick\documents\github\deviation_pi\src\tinyxml/tinyxml.h(65): fatal e
rror C1083: Cannot open include file: 'tinyxml/tinystr.h': No such file or dire
ctory [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
  d:\frederick\documents\github\deviation_pi\src\tinyxml/tinyxml.h(65): fatal e
rror C1083: Cannot open include file: 'tinyxml/tinystr.h': No such file or dire
ctory [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
  d:\frederick\documents\github\deviation_pi\src\tinyxml/tinyxml.h(65): fatal e
rror C1083: Cannot open include file: 'tinyxml/tinystr.h': No such file or dire
ctory [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
  d:\frederick\documents\github\deviation_pi\src\tinyxml/tinyxml.h(65): fatal e
rror C1083: Cannot open include file: 'tinyxml/tinystr.h': No such file or dire
ctory [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
  d:\frederick\documents\github\deviation_pi\src\tinyxml/tinyxml.h(65): fatal e
rror C1083: Cannot open include file: 'tinyxml/tinystr.h': No such file or dire
ctory [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
  D:\Frederick\Documents\GitHub\Deviation_pi\src\jsonval.cpp(32): fatal error C
1083: Cannot open include file: 'wx/jsonval.h': No such file or directory [D:\F
rederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
  d:\frederick\documents\github\deviation_pi\src\tinyxml\tinyxml.h(65): fatal e
rror C1083: Cannot open include file: 'tinyxml/tinystr.h': No such file or dire
ctory [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
  d:\frederick\documents\github\deviation_pi\src\tinyxml\tinyxml.h(65): fatal e
rror C1083: Cannot open include file: 'tinyxml/tinystr.h': No such file or dire
ctory [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
  d:\frederick\documents\github\deviation_pi\src\tinyxml\tinyxml.h(65): fatal e
rror C1083: Cannot open include file: 'tinyxml/tinystr.h': No such file or dire
ctory [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]

    0 Warning(s)
    9 Error(s)

Time Elapsed 00:01:00.38
```

**Comment by rgleason** [comment]
Dirk I have your most recent changes.

1. Needed to move  src/tinystr.h into src/tinyxml/  because of 8 errors.
2. Needed to change the path for jsonval.h  in jsonval.cpp line 32 to remove wx/

//#include <wx/jsonval.h>//
#include <jsonval.h>

but I don't think I should be changing this standard file (?)  maybe it should stay under src/wx?
I don't know enough!
```
  D:\Frederick\Documents\GitHub\Deviation_pi\src\jsonval.cpp(32): fatal error C1083: Cannot open include file: 'wx/jsonval.h': No such file or  directory [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
    1 Warning(s)        1 Error(s)
```

**Comment by rgleason** [comment]
So now after making these changes I get 22 errors:



```
Build FAILED.

"D:\Frederick\Documents\GitHub\Deviation_pi\build\ALL_BUILD.vcxproj" (default target) (1) ->
"D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj" (default target) (3) ->
(Link target) ->
  compass.obj : error LNK2001: unresolved external symbol "public: class TiXmlString & __thiscall TiXmlString::assign(char const *,unsigned in
t)" (?assign@TiXmlString@@QAEAAV1@PBDI@Z) [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
  tinyxml.obj : error LNK2001: unresolved external symbol "public: class TiXmlString & __thiscall TiXmlString::assign(char const *,unsigned in
t)" (?assign@TiXmlString@@QAEAAV1@PBDI@Z) [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
  tinyxmlparser.obj : error LNK2001: unresolved external symbol "public: class TiXmlString & __thiscall TiXmlString::assign(char const *,unsig
ned int)" (?assign@TiXmlString@@QAEAAV1@PBDI@Z) [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
  deviation_pi.obj : error LNK2001: unresolved external symbol "public: class TiXmlString & __thiscall TiXmlString::assign(char const *,unsign
ed int)" (?assign@TiXmlString@@QAEAAV1@PBDI@Z) [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
  SharedStuff.obj : error LNK2001: unresolved external symbol "public: class TiXmlString & __thiscall TiXmlString::assign(char const *,unsigne
d int)" (?assign@TiXmlString@@QAEAAV1@PBDI@Z) [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
  readwritexml.obj : error LNK2001: unresolved external symbol "public: class TiXmlString & __thiscall TiXmlString::assign(char const *,unsign
ed int)" (?assign@TiXmlString@@QAEAAV1@PBDI@Z) [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
  preferencedlg.obj : error LNK2001: unresolved external symbol "public: class TiXmlString & __thiscall TiXmlString::assign(char const *,unsig
ned int)" (?assign@TiXmlString@@QAEAAV1@PBDI@Z) [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
  tinyxml.obj : error LNK2001: unresolved external symbol "public: class TiXmlString & __thiscall TiXmlString::append(char const *,unsigned in
t)" (?append@TiXmlString@@QAEAAV1@PBDI@Z) [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
  tinyxmlparser.obj : error LNK2001: unresolved external symbol "public: class TiXmlString & __thiscall TiXmlString::append(char const *,unsig
ned int)" (?append@TiXmlString@@QAEAAV1@PBDI@Z) [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
  deviation_pi.obj : error LNK2001: unresolved external symbol "public: class TiXmlString & __thiscall TiXmlString::append(char const *,unsign
ed int)" (?append@TiXmlString@@QAEAAV1@PBDI@Z) [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
  SharedStuff.obj : error LNK2001: unresolved external symbol "public: class TiXmlString & __thiscall TiXmlString::append(char const *,unsigne
d int)" (?append@TiXmlString@@QAEAAV1@PBDI@Z) [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
  preferencedlg.obj : error LNK2001: unresolved external symbol "public: class TiXmlString & __thiscall TiXmlString::append(char const *,unsig
ned int)" (?append@TiXmlString@@QAEAAV1@PBDI@Z) [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
  compass.obj : error LNK2001: unresolved external symbol "public: class TiXmlString & __thiscall TiXmlString::append(char const *,unsigned in
t)" (?append@TiXmlString@@QAEAAV1@PBDI@Z) [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
  compass.obj : error LNK2001: unresolved external symbol "private: static struct TiXmlString::Rep TiXmlString::nullrep_" (?nullrep_@TiXmlStri
ng@@0URep@1@A) [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
  tinyxml.obj : error LNK2001: unresolved external symbol "private: static struct TiXmlString::Rep TiXmlString::nullrep_" (?nullrep_@TiXmlStri
ng@@0URep@1@A) [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
  tinyxmlparser.obj : error LNK2001: unresolved external symbol "private: static struct TiXmlString::Rep TiXmlString::nullrep_" (?nullrep_@TiX
mlString@@0URep@1@A) [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
  deviation_pi.obj : error LNK2001: unresolved external symbol "private: static struct TiXmlString::Rep TiXmlString::nullrep_" (?nullrep_@TiXm
lString@@0URep@1@A) [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
  SharedStuff.obj : error LNK2001: unresolved external symbol "private: static struct TiXmlString::Rep TiXmlString::nullrep_" (?nullrep_@TiXml
String@@0URep@1@A) [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
  readwritexml.obj : error LNK2001: unresolved external symbol "private: static struct TiXmlString::Rep TiXmlString::nullrep_" (?nullrep_@TiXm
lString@@0URep@1@A) [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
  preferencedlg.obj : error LNK2001: unresolved external symbol "private: static struct TiXmlString::Rep TiXmlString::nullrep_" (?nullrep_@TiX
mlString@@0URep@1@A) [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
  tinyxml.obj : error LNK2019: unresolved external symbol "public: static unsigned int const TiXmlString::npos" (?npos@TiXmlString@@2IB) refer
enced in function "public: void __thiscall TiXmlAttribute::Print(struct _iobuf *,int,class TiXmlString *)const " (?Print@TiXmlAttribute@@QBEXP
AU_iobuf@@HPAVTiXmlString@@@Z) [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
  D:\Frederick\Documents\GitHub\Deviation_pi\build\Release\deviation_pi.dll : fatal error LNK1120: 4 unresolved externals [D:\Frederick\Docume
nts\GitHub\Deviation_pi\build\deviation_pi.vcxproj]

    0 Warning(s)
    22 Error(s)

It looks like tinystr.h wants to stay in src directory.
```

**Comment by rgleason** [comment]
Now when I build I get these errors:


```
Build FAILED.

"D:\Frederick\Documents\GitHub\Deviation_pi\build\ALL_BUILD.vcxproj" (default target) (1) ->
"D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj" (default target) (3) ->
(ClCompile target) ->
  d:\frederick\documents\github\deviation_pi\src\tinyxml/tinyxml.h(65): fatal error C1083: Cannot open include file: 'tinyxml/tinystr.h': No such file or directory [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
  d:\frederick\documents\github\deviation_pi\src\tinyxml/tinyxml.h(65): fatal error C1083: Cannot open include file: 'tinyxml/tinystr.h': No such file or directory [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
  d:\frederick\documents\github\deviation_pi\src\tinyxml/tinyxml.h(65): fatal error C1083: Cannot open include file: 'tinyxml/tinystr.h': No such file or directory [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
  d:\frederick\documents\github\deviation_pi\src\tinyxml/tinyxml.h(65): fatal error C1083: Cannot open include file: 'tinyxml/tinystr.h': No such file or directory [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
  d:\frederick\documents\github\deviation_pi\src\tinyxml/tinyxml.h(65): fatal error C1083: Cannot open include file: 'tinyxml/tinystr.h': No such file or directory [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
  d:\frederick\documents\github\deviation_pi\src\tinyxml\tinyxml.h(65): fatal error C1083: Cannot open include file: 'tinyxml/tinystr.h': No such file or directory [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
  d:\frederick\documents\github\deviation_pi\src\tinyxml\tinyxml.h(65): fatal error C1083: Cannot open include file: 'tinyxml/tinystr.h': No such file or directory [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
  d:\frederick\documents\github\deviation_pi\src\tinyxml\tinyxml.h(65): fatal error C1083: Cannot open include file: 'tinyxml/tinystr.h': No such file or directory [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]

    0 Warning(s)
    8 Error(s)

```

**Comment by rgleason** [comment]
So this time I left tinystr.h in the src folder  AND copied it to the src/tinyxml  folder.

Then run cmake --build . --config release
and I still get those 22 errors again.


> Build FAILED.
> 
> "D:\Frederick\Documents\GitHub\Deviation_pi\build\ALL_BUILD.vcxproj" (default target) (1) ->
> "D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj" (default target) (3) ->
> (ClCompile target) ->
>   D:\Frederick\Documents\GitHub\Deviation_pi\src\readwritexml.cpp(211): warning C4800: 'int' : forcing value to bool 'true' or 'false' (perfor
> mance warning) [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
> 
> 
> "D:\Frederick\Documents\GitHub\Deviation_pi\build\ALL_BUILD.vcxproj" (default target) (1) ->
> "D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj" (default target) (3) ->
> (Link target) ->
>   compass.obj : error LNK2001: unresolved external symbol "public: class TiXmlString & __thiscall TiXmlString::assign(char const *,unsigned in
> t)" (?assign@TiXmlString@@QAEAAV1@PBDI@Z) [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
>   tinyxml.obj : error LNK2001: unresolved external symbol "public: class TiXmlString & __thiscall TiXmlString::assign(char const *,unsigned in
> t)" (?assign@TiXmlString@@QAEAAV1@PBDI@Z) [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
>   tinyxmlparser.obj : error LNK2001: unresolved external symbol "public: class TiXmlString & __thiscall TiXmlString::assign(char const *,unsig
> ned int)" (?assign@TiXmlString@@QAEAAV1@PBDI@Z) [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
>   deviation_pi.obj : error LNK2001: unresolved external symbol "public: class TiXmlString & __thiscall TiXmlString::assign(char const *,unsign
> ed int)" (?assign@TiXmlString@@QAEAAV1@PBDI@Z) [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
>   SharedStuff.obj : error LNK2001: unresolved external symbol "public: class TiXmlString & __thiscall TiXmlString::assign(char const *,unsigne
> d int)" (?assign@TiXmlString@@QAEAAV1@PBDI@Z) [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
>   readwritexml.obj : error LNK2001: unresolved external symbol "public: class TiXmlString & __thiscall TiXmlString::assign(char const *,unsign
> ed int)" (?assign@TiXmlString@@QAEAAV1@PBDI@Z) [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
>   preferencedlg.obj : error LNK2001: unresolved external symbol "public: class TiXmlString & __thiscall TiXmlString::assign(char const *,unsig
> ned int)" (?assign@TiXmlString@@QAEAAV1@PBDI@Z) [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
>   tinyxml.obj : error LNK2001: unresolved external symbol "public: class TiXmlString & __thiscall TiXmlString::append(char const *,unsigned in
> t)" (?append@TiXmlString@@QAEAAV1@PBDI@Z) [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
>   tinyxmlparser.obj : error LNK2001: unresolved external symbol "public: class TiXmlString & __thiscall TiXmlString::append(char const *,unsig
> ned int)" (?append@TiXmlString@@QAEAAV1@PBDI@Z) [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
>   deviation_pi.obj : error LNK2001: unresolved external symbol "public: class TiXmlString & __thiscall TiXmlString::append(char const *,unsign
> ed int)" (?append@TiXmlString@@QAEAAV1@PBDI@Z) [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
>   SharedStuff.obj : error LNK2001: unresolved external symbol "public: class TiXmlString & __thiscall TiXmlString::append(char const *,unsigne
> d int)" (?append@TiXmlString@@QAEAAV1@PBDI@Z) [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
>   preferencedlg.obj : error LNK2001: unresolved external symbol "public: class TiXmlString & __thiscall TiXmlString::append(char const *,unsig
> ned int)" (?append@TiXmlString@@QAEAAV1@PBDI@Z) [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
>   compass.obj : error LNK2001: unresolved external symbol "public: class TiXmlString & __thiscall TiXmlString::append(char const *,unsigned in
> t)" (?append@TiXmlString@@QAEAAV1@PBDI@Z) [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
>   compass.obj : error LNK2001: unresolved external symbol "private: static struct TiXmlString::Rep TiXmlString::nullrep_" (?nullrep_@TiXmlStri
> ng@@0URep@1@A) [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
>   tinyxml.obj : error LNK2001: unresolved external symbol "private: static struct TiXmlString::Rep TiXmlString::nullrep_" (?nullrep_@TiXmlStri
> ng@@0URep@1@A) [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
>   tinyxmlparser.obj : error LNK2001: unresolved external symbol "private: static struct TiXmlString::Rep TiXmlString::nullrep_" (?nullrep_@TiX
> mlString@@0URep@1@A) [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
>   deviation_pi.obj : error LNK2001: unresolved external symbol "private: static struct TiXmlString::Rep TiXmlString::nullrep_" (?nullrep_@TiXm
> lString@@0URep@1@A) [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
>   SharedStuff.obj : error LNK2001: unresolved external symbol "private: static struct TiXmlString::Rep TiXmlString::nullrep_" (?nullrep_@TiXml
> String@@0URep@1@A) [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
>   readwritexml.obj : error LNK2001: unresolved external symbol "private: static struct TiXmlString::Rep TiXmlString::nullrep_" (?nullrep_@TiXm
> lString@@0URep@1@A) [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
>   preferencedlg.obj : error LNK2001: unresolved external symbol "private: static struct TiXmlString::Rep TiXmlString::nullrep_" (?nullrep_@TiX
> mlString@@0URep@1@A) [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
>   tinyxml.obj : error LNK2019: unresolved external symbol "public: static unsigned int const TiXmlString::npos" (?npos@TiXmlString@@2IB) refer
> enced in function "public: void __thiscall TiXmlAttribute::Print(struct _iobuf *,int,class TiXmlString *)const " (?Print@TiXmlAttribute@@QBEXP
> AU_iobuf@@HPAVTiXmlString@@@Z) [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
>   D:\Frederick\Documents\GitHub\Deviation_pi\build\Release\deviation_pi.dll : fatal error LNK1120: 4 unresolved externals [D:\Frederick\Docume
> nts\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
> 
>     1 Warning(s)
>     22 Error(s)
>

**Comment by rgleason** [comment]
OK,  I put the files  tinystr.h and tinyxml.h under src/ as you had them and deleted tinyxml.h and tinystr.h in src/tinyxml.   -As you had it originally.

Now I get


```
Build FAILED.

"D:\Frederick\Documents\GitHub\Deviation_pi\build\ALL_BUILD.vcxproj" (default target) (1) ->
"D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj" (default target) (3) ->
(ClCompile target) ->
  d:\frederick\documents\github\deviation_pi\src\readwritexml.h(31): fatal error C1083: Cannot open include file: 'tinyxml/tinyxml.h': No such  file or directory [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
  d:\frederick\documents\github\deviation_pi\src\readwritexml.h(31): fatal error C1083: Cannot open include file: 'tinyxml/tinyxml.h': No such  file or directory [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
  d:\frederick\documents\github\deviation_pi\src\readwritexml.h(31): fatal error C1083: Cannot open include file: 'tinyxml/tinyxml.h': No such file or directory [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
  d:\frederick\documents\github\deviation_pi\src\readwritexml.h(31): fatal error C1083: Cannot open include file: 'tinyxml/tinyxml.h': No such file or directory [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
  d:\frederick\documents\github\deviation_pi\src\readwritexml.h(31): fatal error C1083: Cannot open include file: 'tinyxml/tinyxml.h': No such file or directory [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
  D:\Frederick\Documents\GitHub\Deviation_pi\src\tinyxml.h(65): fatal error C1083: Cannot open include file: 'tinyxml/tinystr.h': No such file  or directory [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
  D:\Frederick\Documents\GitHub\Deviation_pi\src\tinyxml.h(65): fatal error C1083: Cannot open include file: 'tinyxml/tinystr.h': No such file  or directory [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
  D:\Frederick\Documents\GitHub\Deviation_pi\src\tinyxml.h(65): fatal error C1083: Cannot open include file: 'tinyxml/tinystr.h': No such file  or directory [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]

    0 Warning(s)
    8 Error(s)
```
This needs fixing:
i\src\readwritexml.h(31): fatal error C1083: Cannot open include file: 'tinyxml/tinyxml.h': No such  file or directory [

**Comment by rgleason** [comment]
Now I get this:

```
Build FAILED.

"D:\Frederick\Documents\GitHub\Deviation_pi\build\ALL_BUILD.vcxproj" (default target) (1) ->
"D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj" (default target) (3) ->
(ClCompile target) ->
  d:\frederick\documents\github\deviation_pi\src\tinyxml.h(65): fatal error C1083: Cannot open include file: 'tinyxml/tinystr.h': No such file
 or directory [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
  d:\frederick\documents\github\deviation_pi\src\tinyxml.h(65): fatal error C1083: Cannot open include file: 'tinyxml/tinystr.h': No such file
 or directory [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
  d:\frederick\documents\github\deviation_pi\src\tinyxml.h(65): fatal error C1083: Cannot open include file: 'tinyxml/tinystr.h': No such file
 or directory [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
  d:\frederick\documents\github\deviation_pi\src\tinyxml.h(65): fatal error C1083: Cannot open include file: 'tinyxml/tinystr.h': No such file
 or directory [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
  d:\frederick\documents\github\deviation_pi\src\tinyxml.h(65): fatal error C1083: Cannot open include file: 'tinyxml/tinystr.h': No such file
 or directory [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
  D:\Frederick\Documents\GitHub\Deviation_pi\src\tinyxml.h(65): fatal error C1083: Cannot open include file: 'tinyxml/tinystr.h': No such file
 or directory [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
  D:\Frederick\Documents\GitHub\Deviation_pi\src\tinyxml.h(65): fatal error C1083: Cannot open include file: 'tinyxml/tinystr.h': No such file
 or directory [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
  D:\Frederick\Documents\GitHub\Deviation_pi\src\tinyxml.h(65): fatal error C1083: Cannot open include file: 'tinyxml/tinystr.h': No such file
 or directory [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]

    0 Warning(s)
    8 Error(s)

```

**Comment by rgleason** [comment]
So now changed tinyxml.h
Line 65 after the ELSE to 

//	#include "tinyxml/tinystr.h"//
	#include "tinystr.h"

**Comment by rgleason** [comment]
So now I get this again:


```
Build FAILED.

"D:\Frederick\Documents\GitHub\Deviation_pi\build\ALL_BUILD.vcxproj" (default target) (1) ->
"D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj" (default target) (3) ->
(ClCompile target) ->
  D:\Frederick\Documents\GitHub\Deviation_pi\src\readwritexml.cpp(211): warning C4800: 'int' : forcing value to bool 'true' or 'false' (perfor
mance warning) [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]


"D:\Frederick\Documents\GitHub\Deviation_pi\build\ALL_BUILD.vcxproj" (default target) (1) ->
"D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj" (default target) (3) ->
(Link target) ->
  compass.obj : error LNK2001: unresolved external symbol "public: class TiXmlString & __thiscall TiXmlString::assign(char const *,unsigned in
t)" (?assign@TiXmlString@@QAEAAV1@PBDI@Z) [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
  tinyxml.obj : error LNK2001: unresolved external symbol "public: class TiXmlString & __thiscall TiXmlString::assign(char const *,unsigned in
t)" (?assign@TiXmlString@@QAEAAV1@PBDI@Z) [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
  tinyxmlparser.obj : error LNK2001: unresolved external symbol "public: class TiXmlString & __thiscall TiXmlString::assign(char const *,unsig
ned int)" (?assign@TiXmlString@@QAEAAV1@PBDI@Z) [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
  deviation_pi.obj : error LNK2001: unresolved external symbol "public: class TiXmlString & __thiscall TiXmlString::assign(char const *,unsign
ed int)" (?assign@TiXmlString@@QAEAAV1@PBDI@Z) [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
  SharedStuff.obj : error LNK2001: unresolved external symbol "public: class TiXmlString & __thiscall TiXmlString::assign(char const *,unsigne
d int)" (?assign@TiXmlString@@QAEAAV1@PBDI@Z) [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
  readwritexml.obj : error LNK2001: unresolved external symbol "public: class TiXmlString & __thiscall TiXmlString::assign(char const *,unsign
ed int)" (?assign@TiXmlString@@QAEAAV1@PBDI@Z) [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
  preferencedlg.obj : error LNK2001: unresolved external symbol "public: class TiXmlString & __thiscall TiXmlString::assign(char const *,unsig
ned int)" (?assign@TiXmlString@@QAEAAV1@PBDI@Z) [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
  tinyxml.obj : error LNK2001: unresolved external symbol "public: class TiXmlString & __thiscall TiXmlString::append(char const *,unsigned in
t)" (?append@TiXmlString@@QAEAAV1@PBDI@Z) [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
  tinyxmlparser.obj : error LNK2001: unresolved external symbol "public: class TiXmlString & __thiscall TiXmlString::append(char const *,unsig
ned int)" (?append@TiXmlString@@QAEAAV1@PBDI@Z) [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
  deviation_pi.obj : error LNK2001: unresolved external symbol "public: class TiXmlString & __thiscall TiXmlString::append(char const *,unsign
ed int)" (?append@TiXmlString@@QAEAAV1@PBDI@Z) [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
  SharedStuff.obj : error LNK2001: unresolved external symbol "public: class TiXmlString & __thiscall TiXmlString::append(char const *,unsigne
d int)" (?append@TiXmlString@@QAEAAV1@PBDI@Z) [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
  preferencedlg.obj : error LNK2001: unresolved external symbol "public: class TiXmlString & __thiscall TiXmlString::append(char const *,unsig
ned int)" (?append@TiXmlString@@QAEAAV1@PBDI@Z) [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
  compass.obj : error LNK2001: unresolved external symbol "public: class TiXmlString & __thiscall TiXmlString::append(char const *,unsigned in
t)" (?append@TiXmlString@@QAEAAV1@PBDI@Z) [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
  compass.obj : error LNK2001: unresolved external symbol "private: static struct TiXmlString::Rep TiXmlString::nullrep_" (?nullrep_@TiXmlStri
ng@@0URep@1@A) [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
  tinyxml.obj : error LNK2001: unresolved external symbol "private: static struct TiXmlString::Rep TiXmlString::nullrep_" (?nullrep_@TiXmlStri
ng@@0URep@1@A) [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
  tinyxmlparser.obj : error LNK2001: unresolved external symbol "private: static struct TiXmlString::Rep TiXmlString::nullrep_" (?nullrep_@TiX
mlString@@0URep@1@A) [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
  deviation_pi.obj : error LNK2001: unresolved external symbol "private: static struct TiXmlString::Rep TiXmlString::nullrep_" (?nullrep_@TiXm
lString@@0URep@1@A) [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
  SharedStuff.obj : error LNK2001: unresolved external symbol "private: static struct TiXmlString::Rep TiXmlString::nullrep_" (?nullrep_@TiXml
String@@0URep@1@A) [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
  readwritexml.obj : error LNK2001: unresolved external symbol "private: static struct TiXmlString::Rep TiXmlString::nullrep_" (?nullrep_@TiXm
lString@@0URep@1@A) [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
  preferencedlg.obj : error LNK2001: unresolved external symbol "private: static struct TiXmlString::Rep TiXmlString::nullrep_" (?nullrep_@TiX
mlString@@0URep@1@A) [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
  tinyxml.obj : error LNK2019: unresolved external symbol "public: static unsigned int const TiXmlString::npos" (?npos@TiXmlString@@2IB) refer
enced in function "public: void __thiscall TiXmlAttribute::Print(struct _iobuf *,int,class TiXmlString *)const " (?Print@TiXmlAttribute@@QBEXP
AU_iobuf@@HPAVTiXmlString@@@Z) [D:\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
  D:\Frederick\Documents\GitHub\Deviation_pi\build\Release\deviation_pi.dll : fatal error LNK1120: 4 unresolved externals [D:\Frederick\Docume
nts\GitHub\Deviation_pi\build\deviation_pi.vcxproj]

    1 Warning(s)
    22 Error(s)

```

**Comment by rgleason** [comment]
Now I am thinking all the tinyxml and tinystr  should be under tinyxml directory and the paths fixed.

**Comment by rgleason** [comment]
I also think the src/wx/  directory for json should be used so those files remain standard too.

**Comment by RooieDirk** [comment]
Rick,
You have been busy. The problem with the missing "tinystr.h: file is a missing line in the CmakeText. (corrected now). I started the code with a copy of the wmm plugin, and as this PI is always compiled as part of O it doesn't hurt there.
For the wxJson is AFAIK not an official part of wxWidgets, and it should indeed be changed from #include <wx.jsonvalue.h> to #include "jsonvalue.h"

I also tried stand alone, And compiling works, but get a linking error. Somthing with the Opencpn.lib or so. Terrible system windows:-)

Above changes are on git now

**Comment by rgleason** [comment]
I agree, windows is very picky, or at least the compiler is. Will try it when I get into Boston.
Thanks

**Comment by rgleason** [comment]
Dirk,
I think the problem with the bad links is probably we are missing ocpn_h.lib?
Hope that's it.
I have to clone your repos again and try it, when I get a chance.
I think I have everything needed for buildwin directory, because I copied the opencpn buildwin and I do have opencpn.lib from verision 4.2 which should be fine  (125kb)

**Comment by rgleason** [comment]
I actually ment "ocpn_plugin.h" and you have that in src now, along with other directories.
Deleted my local repos and git cloned, put opencpn.lib in a new build directory and tried it.

Sorry, Still get 85 link type errors.  These objects must exist because they are basic to the plugin. Somehow their existence is not being communicated. I don't understand how C++ is wired, but is there some include needed at the head of some file?

  bearingdlg.obj : error LNK2001: unresolved external symbol "public: virtual b
ool __thiscall PlugInChartBaseExtended::RenderRegionViewOnDCTextOnly(class wxMe
moryDC &,class PlugIn_ViewPort const &,class wxRegion const &)" (?RenderRegionV
iewOnDCTextOnly@PlugInChartBaseExtended@@UAE_NAAVwxMemoryDC@@ABVPlugIn_ViewPort
@@ABVwxRegion@@@Z) [C:\Users\Frederick\Documents\GitHub\Deviation_pi\build\devi
ation_pi.vcxproj]

  deviation_pi.obj : error LNK2001: unresolved external symbol "public: virtual
 bool __thiscall PlugInChartBaseExtended::RenderRegionViewOnDCTextOnly(class wx
MemoryDC &,class PlugIn_ViewPort const &,class wxRegion const &)" (?RenderRegio
nViewOnDCTextOnly@PlugInChartBaseExtended@@UAE_NAAVwxMemoryDC@@ABVPlugIn_ViewPo
rt@@ABVwxRegion@@@Z) [C:\Users\Frederick\Documents\GitHub\Deviation_pi\build\de
viation_pi.vcxproj]

  SharedStuff.obj : error LNK2001: unresolved external symbol "public: virtual
bool __thiscall PlugInChartBaseExtended::RenderRegionViewOnDCTextOnly(class wxM
emoryDC &,class PlugIn_ViewPort const &,class wxRegion const &)" (?RenderRegion
ViewOnDCTextOnly@PlugInChartBaseExtended@@UAE_NAAVwxMemoryDC@@ABVPlugIn_ViewPor
t@@ABVwxRegion@@@Z) [C:\Users\Frederick\Documents\GitHub\Deviation_pi\build\dev
iation_pi.vcxproj]

  preferencedlg.obj : error LNK2001: unresolved external symbol "public: virtua
l bool __thiscall PlugInChartBaseExtended::RenderRegionViewOnDCTextOnly(class w
xMemoryDC &,class PlugIn_ViewPort const &,class wxRegion const &)" (?RenderRegi
onViewOnDCTextOnly@PlugInChartBaseExtended@@UAE_NAAVwxMemoryDC@@ABVPlugIn_ViewP
ort@@ABVwxRegion@@@Z) [C:\Users\Frederick\Documents\GitHub\Deviation_pi\build\d
eviation_pi.vcxproj]

  compass.obj : error LNK2001: unresolved external symbol "public: virtual bool
 __thiscall PlugInChartBaseExtended::RenderRegionViewOnDCTextOnly(class wxMemor
yDC &,class PlugIn_ViewPort const &,class wxRegion const &)" (?RenderRegionView
OnDCTextOnly@PlugInChartBaseExtended@@UAE_NAAVwxMemoryDC@@ABVPlugIn_ViewPort@@A
BVwxRegion@@@Z) [C:\Users\Frederick\Documents\GitHub\Deviation_pi\build\deviati
on_pi.vcxproj]

  printing.obj : error LNK2001: unresolved external symbol "public: virtual int
 __thiscall PlugInChartBaseExtended::RenderRegionViewOnGLNoText(class wxGLConte
xt const &,class PlugIn_ViewPort const &,class wxRegion const &,bool)" (?Render
RegionViewOnGLNoText@PlugInChartBaseExtended@@UAEHABVwxGLContext@@ABVPlugIn_Vie
wPort@@ABVwxRegion@@_N@Z) [C:\Users\Frederick\Documents\GitHub\Deviation_pi\bui
ld\deviation_pi.vcxproj]

  bearingdlg.obj : error LNK2001: unresolved external symbol "public: virtual i
nt __thiscall PlugInChartBaseExtended::RenderRegionViewOnGLNoText(class wxGLCon
text const &,class PlugIn_ViewPort const &,class wxRegion const &,bool)" (?Rend
erRegionViewOnGLNoText@PlugInChartBaseExtended@@UAEHABVwxGLContext@@ABVPlugIn_V
iewPort@@ABVwxRegion@@_N@Z) [C:\Users\Frederick\Documents\GitHub\Deviation_pi\b
uild\deviation_pi.vcxproj]

**Comment by rgleason** [comment]
You left a dll and I'll try that. Thanks.

**Comment by rgleason** [comment]
Dirk, I asked Mike if he had any idea, because he see's things I don't re win install.
I don't have yor email 

Rick ... (Please forward to Dirk)

Decided to use my own 'ocpn_plugin.h' and 'opencpn.lib'. Compiled without a problem. Could you see if the .h and .lib attached solve the issue.

'table.png' shows the result.

'wmm_pi' was not present for my first run of the plugin. 'nan.png' shows the effect. Dirk needs to allow for this I think.

It would be nice to have standard buttons on the plugin forms ('minmaxclose.png').

Coefficients with 6 decimal places is a little excessive. 1 would have been sufficient.

Entering the results from a recent compass swing I carried out on a motor yacht was a good exercise. It took a while to convert the bearings of marks to true. I tend to think magnetic when carrying out a swing using shore transits. Would the option of an additional box for magnetic bearing of the mark be useful? The calculation could use magnetic and compass and calculate the deviation easily.

This is going to be a useful addition to the plugins.

Mike


On 13/12/2017 12:59, Rick Gleason wrote:
> Dear Mike
>
> Dirk and I are having troubles getting this to compile and we are getting link errors of this type now.
>
> I think he has all the directories needed now and ocpn_plugin.h in src
>
> Do you have any idea/suggestions for us?
>
> He's left a dll in there to test, which I will use, but the question remains.
>
> https://github.com/RooieDirk/Deviation_pi/issues/1
>
> Thanks
>
> Rick
>

![nan](https://user-images.githubusercontent.com/2363959/33957329-53f4dfae-e00f-11e7-8e03-7eeb1166a4f1.png)
![minmaxclose](https://user-images.githubusercontent.com/2363959/33957330-541cc550-e00f-11e7-8323-986998cb0d8a.png)

![table](https://user-images.githubusercontent.com/2363959/33957331-54845a58-e00f-11e7-8164-cd5981381172.png)

Please take the pdf off of these.
[opencpn.lib.pdf](https://github.com/RooieDirk/Deviation_pi/files/1556706/opencpn.lib.pdf)
[deviation_pi.dll.pdf](https://github.com/RooieDirk/Deviation_pi/files/1556707/deviation_pi.dll.pdf)
[ocpn_plugin.h.pdf](https://github.com/RooieDirk/Deviation_pi/files/1556708/ocpn_plugin.h.pdf)

**Comment by rgleason** [comment]
Dirk,
I git fetched and tried it with Mike's ocpn_plugin.h  and it compiled.  that file is 45kb.



Build succeeded.

"C:\Users\Frederick\Documents\GitHub\Deviation_pi\build\ALL_BUILD.vcxproj" (def
ault target) (1) ->
"C:\Users\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj" (
default target) (3) ->
(ClCompile target) ->
  C:\Users\Frederick\Documents\GitHub\Deviation_pi\src\readwritexml.cpp(211): w
arning C4800: 'int' : forcing value to bool 'true' or 'false' (performance warn
ing) [C:\Users\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxpr
oj]

    1 Warning(s)
    0 Error(s)

**Comment by rgleason** [comment]
made an installer too.
I think that was it. Will try it later.

**Comment by rgleason** [comment]
Dirk, git fetched and merged
Now at  RooieDirk beta 2, Make sure pointer to dlg are reset to null if dlg is closed   Latest commit 99550b6


```
Build FAILED.

"C:\Users\Frederick\Documents\GitHub\Deviation_pi\build\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\Users\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj" (default target) (3) ->
(ClCompile target) ->
  c:\users\frederick\documents\github\deviation_pi\src\deviation_pi.h(85): error C2504: 'opencpn_plugin_114' : base class undefined [C:\Users\Frederick\Documents\Gi
tHub\Deviation_pi\build\deviation_pi.vcxproj]
  c:\users\frederick\documents\github\deviation_pi\src\deviation_pi.h(85): error C2504: 'opencpn_plugin_114' : base class undefined [C:\Users\Frederick\Documents\Gi
tHub\Deviation_pi\build\deviation_pi.vcxproj]
  c:\users\frederick\documents\github\deviation_pi\src\deviation_pi.h(85): error C2504: 'opencpn_plugin_114' : base class undefined [C:\Users\Frederick\Documents\Gi
tHub\Deviation_pi\build\deviation_pi.vcxproj]
  C:\Users\Frederick\Documents\GitHub\Deviation_pi\src\deviation_pi.cpp(117): error C2440: 'return' : cannot convert from 'deviation_pi *' to 'opencpn_plugin *' [C:
\Users\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
  C:\Users\Frederick\Documents\GitHub\Deviation_pi\src\deviation_pi.cpp(141): error C2614: 'deviation_pi' : illegal member initialization: 'opencpn_plugin_114' is n
ot a base or member [C:\Users\Frederick\Documents\GitHub\Deviation_pi\build\deviation_pi.vcxproj]
  C:\Users\Frederick\Documents\GitHub\Deviation_pi\src\deviation_pi.cpp(180): error C2664: 'int InsertPlugInTool(wxString,wxBitmap *,wxBitmap *,wxItemKind,wxString,
wxString,wxObject *,int,int,opencpn_plugin *)' : cannot convert argument 10 from 'deviation_pi *const ' to 'opencpn_plugin *' [C:\Users\Frederick\Documents\GitHub\D
eviation_pi\build\deviation_pi.vcxproj]

    0 Warning(s)
    6 Error(s) 
```

**Comment by rgleason** [comment]
These are old notes.  The code has changed. I am closing.
